### STAGE 1: Build ###
FROM node:18-alpine AS build
ARG BUILDSTAGE
WORKDIR /usr/src/app
COPY package.json  ./
RUN npm install
COPY . .
RUN if [[ -z "${BUILDSTAGE}" ]] ; then  npm run build ; else  npm run ${BUILDSTAGE} ; fi

### STAGE 2: Run ###
FROM nginx:1.19.6-alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
RUN chown nginx /usr/share/nginx/html -R
